Vagrant.configure("2") do |config|
  config.vm.box = "bedin"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 6
  end

  config.vm.define "dev" do |dev|
    dev.vm.hostname = "bedin"
  end
end