Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 6
  end

  config.vm.synced_folder "readonly/", "/vagrant/readonly", mount_options: ["dmode=777,fmode=666"]

  config.vm.define "dev" do |dev|
    dev.vm.hostname = "dev"
    dev.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbooks/playbook-vm.yaml"
      ansible.vault_password_file = "readonly/.vault_pass.txt"
    end

    dev.vm.provision "shell", reboot: true, path: "scripts/setup.sh"
  end
end