- hosts: localhost
  tasks:
    - name: Setup Repos
      become: true
      ansible.builtin.shell: |
        # Vagrant repository
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor |  tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" |  tee /etc/apt/sources.list.d/hashicorp.list

        # Kubectl repository
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list

        apt-get update

    - name: Install Vagrant
      become: true
      ansible.builtin.apt:
        pkg:
          - vagrant
          - kubectl

    - name: Install Go
      ansible.builtin.shell: |
        curl "https://go.dev/dl/go1.21.4.src.tar.gz"
        tar -C /usr/local -xzf go1.21.4.linux-amd64.tar.gz
        rm go1.21.4.linux-amd64.tar.gz

    - name: Vagrant Plugins
      ansible.builtin.shell: |
        vagrant plugin install vagrant-libvirt
