- hosts: localhost
  tasks:
    - name: Setup Repos
      become: true
      ansible.builtin.shell: |
        # Vagrant repository
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor |  tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" |  tee /etc/apt/sources.list.d/hashicorp.list

        apt-get update

    - name: Install Vagrant
      become: true
      ansible.builtin.apt:
        pkg:
          - vagrant
          - kubectl

    - name: Install Go
      become: true
      ansible.builtin.shell: |
        wget https://go.dev/dl/go1.22.0.linux-amd64.tar.gz
        tar -C /usr/local -xzf go1.22.0.linux-amd64.tar.gz
        rm go1.22.0.linux-amd64.tar.gz

    - name: Install K8S
      become: true
      ansible.builtin.shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        rm kubectl
        
    - name: Install kubectx and kubens
        git clone https://github.com/ahmetb/kubectx /opt/kubectx
        ln -s /opt/kubectx/kubectx /usr/local/bin/kubectx
        ln -s /opt/kubectx/kubens /usr/local/bin/kubens

    - name: Install Kind and Helm
      ansible.builtin.shell: |
        go install sigs.k8s.io/kind@v0.22.0
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Vagrant Plugins
      ansible.builtin.shell: |
        vagrant plugin install vagrant-libvirt
