- hosts: localhost
  become: yes
  vars:
    - user: 'guilhermeb'
    - ssh_key: '~/.ssh/id_rsa'
  tasks:
    - name: Install base packages
      ansible.builtin.apt:
        pkg:
          - zsh
          - ca-certificates 
          - curl 
          - gnupg
          - terminator
          - neovim
          - nfs-kernel-server
          - qemu-kvm 
          - libvirt-daemon-system 
          - build-essential 
          - libxslt-dev 
          - libxml2-dev 
          - libvirt-dev 
          - zlib1g-dev 
          - ruby-dev
          - virt-manager

    - name: Change shell to zsh
      ansible.builtin.shell: |
        chsh -s $(which zsh)

    - name: Install oh my zsh
      ansible.builtin.shell: |
        sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    - name: Setup Necessary Repos
      ansible.builtin.shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg

        # Docker Repository
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        
        # Vagrant repository
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

        # Kubectl repository
        curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

        apt-get update
    
    - name: Install Docker, Vagrant, Kubecetl and Containerd
      ansible.builtin.apt:
        pkg:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
          - docker-buildx-plugin 
          - docker-compose-plugin
          - vagrant
          - kubectl

    - name: Setup docker, libvirt and nfs-kernel-server
      ansible.builtin.shell: |
        groupadd docker
        usermod -aG docker guilhermeb
        systemctl enable docker.service
        systemctl enable containerd.service
        systemctl enable nfs-kernel-server.service

    - name: Setup Neovim
      ansible.builtin.git:
        repo: ngit@github.com:guibedin/nvim.git
        dest: ~/.config/nvim
