- hosts: localhost
  become: yes
  vars:
    - user: 'guilhermeb'
  tasks:
    - name: Install base packages
      ansible.builtin.apt:
        pkg:
          - wget
          - zsh
          - ca-certificates 
          - curl 
          - gnupg
          - terminator
          - neovim
          - nfs-kernel-server
          - qemu-kvm 
          - libvirt-daemon-system 
          - build-essential 
          - libxslt-dev 
          - libxml2-dev 
          - libvirt-dev 
          - zlib1g-dev 
          - ruby-dev
          - virt-manager
          - apt-transport-https
          - tmux

    - name: Change shell to zsh
      ansible.builtin.shell: |
        chsh -s $(which zsh)

    - name: Install oh my zsh
      ansible.builtin.shell: |
        sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    - name: Setup Necessary Repos
      ansible.builtin.shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg

        # Docker Repository
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
           tee /etc/apt/sources.list.d/docker.list > /dev/null
        
        # Vagrant repository
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor |  tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" |  tee /etc/apt/sources.list.d/hashicorp.list

        # Kubectl repository
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list

        apt-get update
    
    - name: Install Docker, Vagrant, Kubecetl and Containerd
      ansible.builtin.apt:
        pkg:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
          - docker-buildx-plugin 
          - docker-compose-plugin
          - vagrant
          - kubectl

    - name: Setup docker, libvirt and nfs-kernel-server
      ansible.builtin.shell: |
        groupadd docker
        usermod -aG docker guilhermeb
        systemctl enable docker.service
        systemctl enable containerd.service
        systemctl enable nfs-kernel-server.service

    - name: Setup Neovim
      become: false
      ansible.builtin.git:
        repo: git@github.com:guibedin/nvim.git
        dest: ~/.config/nvim
        key_file: ~/.ssh/id_rsa

    - name: Install Go
      ansible.builting.sh: |
        curl "https://go.dev/dl/go1.21.4.src.tar.gz"
        tar -C /usr/local -xzf go1.21.4.linux-amd64.tar.gz
        rm go1.21.4.linux-amd64.tar.gz

    - name: Create symlinks
      ansible.builting.sh: |
        ln -s ~/personal/setup/dotfiles/.tmux.conf ~/.tmux.conf
        ln -s ~/personal/setup/dotfiles/.zshrc ~/.zshrc
        ln -s ~/personal/setup/dotfiles/.tmux-cht-command ~/.tmux-cht-command
        ln -s ~/personal/setup/dotfiles/.tmux-cht-languages ~/.tmux-cht-languages
        ln -s ~/personal/setup/scripts/tmux-sessionizer.sh ~/.local/bin/tmux-sessionizer

